import express from "express";
import * as blogCtrl from "../controllers/blogController.js";
import auth from "../middleware/auth.js";
const router = express.Router();
router.get('/', blogCtrl.getBlogs);
router.get('/:id', blogCtrl.getBlogById);
router.post('/', auth, blogCtrl.createBlog);
router.put('/:id', auth, blogCtrl.updateBlog);
router.delete('/:id', auth, blogCtrl.deleteBlog);
export default router;